Real-Dev-Squad/website-calendar

- README.md
Update the README.md file to allow new users to follow the steps to start contributing to the repo.
No 
- Expected
- Actual
> Updation of the README.md file to allow new users to follow the steps to start contributing to the repo.

- app/components/Button.tsx
- app/components/SocialAuth.tsx
- app/components/icons/Google.tsx
- app/components/icons/Microsoft.tsx
- app/components/icons/index.tsx
- app/models/oauth.server.ts
- app/routes/login.tsx
- app/routes/signup.tsx
- app/stories/Button.stories.tsx
- app/styles/tailwind.css
- app/types/Icon.ts
- package.json
- tailwind.config.js
- yarn.lock
- Created `/login` & `/signup` routes and integrated Google and Microsoft OAuth on both pages.
- Changed the `tailwind.config.js` to prevent the default colors from tailwind from being overwritten. 
- Created a `LinkButton` in `Component/Button.tsx` to use in login & signup pages & for any other links that should be styled as buttons. 
For this feature to work we should add the following keys to `.env`.
- GOOGLE_OAUTH_LINK
- MICROSOFT_OAUTH_LINK
NO
- Expected
- Actual
> Made Login & Signup pages

- app/components/common/userInput/index.tsx
- app/styles/tailwind.css
added fix for userinput component breaking if it contains a button component
yes
Chrome
](https://user-images.githubusercontent.com/68243599/209499846-67fca26e-e793-491e-b890-f0e1532960fc.png)
> added fix for userInput component 

- app/components/common/userInput/index.tsx
- app/routes/ForgotPassword.tsx
- app/routes/OtpVerification.tsx
- app/routes/ResetPassword.tsx
fix for login screens
- updated file names
- updated imports
- Expected
- Actual
> fix: update file names, imports

- app/components/common/navbar/index.tsx
- app/root.tsx
- app/styles/tailwind.css
- package.json
- yarn.lock
- removes the old tui calendar package
- removes the css import of tui calendar package
- addresses a typo in `navbar` component
Closes #116
No
> refactor: remove package and imports

- .storybook/main.js
- README.md
- app/stories/eventCard.stories.tsx
- app/styles/tailwind.css
While running a storybook, server was not started with error message of "ModuleNotFoundError" as we have not configured path Alias in Storybook. In this PR, I have configured Storybook to resolve path alias. 
This PR closes issue ticket #138
> Fix: alias error while running storybook

- app/styles/global.css
- app/styles/tailwind.css
update the color of event card
No
closes #110
> style: update event card color

- .eslintrc.js
- .prettierrc.json
- app/api/onboarding/username.client.ts
- app/components/Calendar.tsx
- app/components/common/dropdown/index.test.tsx
- app/components/common/emailChipsInput/index.test.tsx
- app/components/common/emailChipsInput/index.tsx
- app/components/common/eventModal/index.test.tsx
- app/components/common/eventModal/index.tsx
- app/components/common/eventVisibility/index.tsx
- app/components/common/rdsCalendar/index.test.tsx
- app/components/common/rdsCalendar/index.tsx
- app/components/common/userInput/index.tsx
- app/env.server.ts
Updated the eslint and prettier config and removed all the es-lint disable commands
- Expected
- Actual
> fix: eslint prettier configs

- app/entry.client.tsx
- app/mocks/browser.ts
- app/mocks/handlers/handlers.ts
- app/mocks/handlers/users.handler.ts
- app/mocks/server.ts
- jest.setup.js
- package.json
- public/mockServiceWorker.js
- yarn.lock
> added msw setup for browser (#149)

- app/components/Calendar.tsx
- app/constants/urls.constants.ts
- app/data/events.data.ts
- app/routes/index.tsx
- app/store/eventSlice.ts
- app/store/userSlice.ts
- app/styles/global.css
- app/utils/event.utils.ts
- app/utils/interfaces.ts
- yarn.lock
integrating the get events API
No
- Expected
- Actual
closes #125 , #136 , and #139
> feat: integrate get events API

- app/components/common/eventModal/index.tsx
- app/components/common/userInput/index.tsx
- app/routes/index.tsx
- app/styles/tailwind.css
Added hot bug fixes for, eventModal and API calls for event page.
> Added hot bug fixes for, eventModal and API calls for event page.

- app/api/onboarding/username.client.ts
- app/routes/index.tsx
> isUsernameAvailable function change and logs

- app/routes/index.tsx
Display to user the related user message in case user self data or ownerID details are missing
- Expected
- Actual
> hotfix: debug issue related to signup

- app/components/SocialAuth.tsx
- app/routes/event/$eventId.tsx
- app/routes/index.tsx
- app/routes/login.tsx
> API Integration & Redirect user to login  changes

- app/components/SocialAuth.tsx
- app/routes/index.tsx
… callback url
- We were redirecting the user to the login page even if the account was created and a cookie was set if the username was absent. 
- Changed this to redirect the user to the `/login` route only if user details are not present and redirect them to `/onboarding` if the username is not set. 
- Expected
- Actual
> Add check for user and username, change hardcoded google login url to the callback url

- app/components/common/eventModal/index.tsx
set state was not properly updated when the structure was changed. updated the set state structure accordingly.
- Expected
- Actual
> fix event modal bug

- app/routes/onboarding.tsx
- app/routes/onboarding/userDetails.tsx
commented step 2 of onboarding and redirected user to homepage.
closes #185
> refactor: comment onboarding step2

- app/constants/socialEvents.constants.ts
> chore: add public event to calendar site

- app/components/common/dropdown/index.tsx
- app/components/common/navbar/index.tsx
- app/styles/tailwind.css
> Minor: User Feedback Fix

- app/components/common/eventModal/index.tsx
- app/constants/events.constants.ts
- app/routes/event/$eventId.tsx
- app/styles/tailwind.css
- check if `routerLocation` has state before accessing properties on it
- add 30 mins to `dummyEvent.end`
- Expected
- Actual
> fix undefined event

- app/components/common/eventModal/index.tsx
- app/routes/index.tsx
> Introduction of cache header, toast message changes

- app/routes/index.tsx
> Removal of cache from Header Function 

- app/components/common/rdsCalendar/index.tsx
- app/constants/urls.constants.ts
- app/routes/index.tsx
- app/routes/onboarding/userDetails.tsx
- app/utils/cookie.utils.ts
- app/utils/event.utils.ts
- dependent on https://github.com/Real-Dev-Squad/calendar-API/pull/100
- we were making 3 sequential api calls to backend on homepage route which was significantly delaying the loading of the page as these calls were on server-side of remix
- optimized the login flow
- moved relevant details to cookies (username, calendarId)
- moved getEvents call from server-side to frontend
- Expected
- Actual
Closes #167 , #182 , #187 , #195 , #197 , #198 , #202
> refactor: optimize homepage

- app/components/common/dropdown/index.tsx
- app/components/common/emailChipsInput/index.tsx
- app/components/common/eventModal/index.tsx
- app/components/common/eventVisibility/EventVisibilitySetter.test.tsx
- app/components/common/eventVisibility/EventVisibilitySetter.tsx
- app/components/common/eventVisibility/index.test.tsx
- app/components/common/eventVisibility/index.tsx
- app/components/common/rdsCalendar/index.tsx
- app/components/common/spinner/index.test.tsx
- app/components/common/spinner/index.tsx
- app/components/common/userInput/index.tsx
- app/routes/onboarding/userDetails.tsx
- app/store/eventSlice.ts
- app/styles/tailwind.css
- Spinner
- After API calls from FE (submit on onboarding, clicking on event from calendar, submit on event modal)
- no package used - dynamic spinner - shows current date
- Event Modal UI upgrades
- update title to look like an input field
- update Event Visibility to look like a switch (created a separate component to set visibility. Existing one will be used to only show the visibility of an event)
- After logging in, instead of showing the current date and event, the user is getting redirected to the date when the 1st event was created
- Added keyboard accessibility to dropdown in onboarding
- Expected
- Actual
> For visual or interaction changes. Can be video / …
> fix: ui ux bugs
